#!/bin/python3

import csv
#https://docs.python.org/3/library/csv.html
with open('Mycsv.csv', 'w', newline='') as csvfile:
    fieldnames = ['first_name', 'last_name', 'username', 'password']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

    writer.writeheader()
    writer.writerow({'first_name': 'Baked', 'last_name': 'Beans', 'username':'bbeans@email.com', 'password':'testpassword'})
    writer.writerow({'first_name': 'Lovely', 'last_name': 'Spam','username':'lspam@email.com', 'password':'testpassword'})
    writer.writerow({'first_name': 'Wonderful', 'last_name': 'Spam','username':'wspam@email.com', 'password':'testpassword'})